spring:
  profiles:
    active:
    - CAT
    - ENG
    - prod
guru:
  username: ymlExampleUser
  password: ymlExamplePassword
  jdbcurl: ymlExampleUrlForDb

hello:
  username: ymlHelloExampleUser
  password: ymlHelloExamplePassword
  jdbcurl: ymlHelloExampleUrlForDb


---
spring:
  profiles: prod

guru:
  username: ymlPrdExampleUser
  password: ymlPrdExamplePassword
  jdbcurl: ymlPrdExampleUrlForDb
