spring:
  profiles:
    active:
    - CAT
    - ENG
    - prod
guru:
  username: ymlExampleUser
  password: ymlExamplePassword
  jdbcurl: ymlExampleUrlForDb


---
spring:
  profiles: prod

guru:
  username: ymlPrdExampleUser
  password: ymlPrdExamplePassword
  jdbcurl: ymlPrdExampleUrlForDb
